openapi: "3.0.2"
info:
  title: Sunrise Alarm - Common components
  version: "1.0"

paths: {}

components:
  schemas:
    Alarm:
      type: object
      required:
        - id
        - enabled
        - name
        - hour
        - minute
        - days
        - skip_next
      properties:
        id:
          type: string
          format: uuid
        enabled:
          type: boolean
        name:
          type: string
        hour:
          type: integer
        minute:
          type: integer
        days:
          type: array
          items:
            type: integer
            minimum: 0 # Monday
            maximum: 6 # Sunday
        skip_next:
          type: boolean

    NextAlarm:
      type: object
      required:
        - id
        - alarm_datetime
        - next_action
        - next_action_datetime
      properties:
        id:
          type: string
          format: uuid
        alarm_datetime:
          type: string
          format: date-time
        next_action:
          $ref: "#/components/schemas/NextAction"
        next_action_datetime:
          type: string
          format: date-time

    NextAction:
      type: string
      enum:
        - NONE
        - RING
        - SKIP

    NextAlarms:
      type: object
      properties:
        ring:
          $ref: "#/components/schemas/NextAlarm"
        action:
          $ref: "#/components/schemas/NextAlarm"
