// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Button is an autogenerated mock type for the Button type
type Button struct {
	mock.Mock
}

// IsPressed provides a mock function with given fields:
func (_m *Button) IsPressed() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
