// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MQTTClient is an autogenerated mock type for the MQTTClient type
type MQTTClient struct {
	mock.Mock
}

// Publish provides a mock function with given fields: ctx, topic, payload
func (_m *MQTTClient) Publish(ctx context.Context, topic string, payload string) error {
	ret := _m.Called(ctx, topic, payload)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, topic, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
