version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly

  # Maintain dependencies for Golang
  - package-ecosystem: gomod
    directory: /src
    schedule:
      interval: weekly

  # Maintain dependencies for NPM (vendors)
  - package-ecosystem: npm
    directory: /src
    schedule:
      interval: weekly
