// Code generated by mockery v2.12.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	testing "testing"
)

// Button is an autogenerated mock type for the Button type
type Button struct {
	mock.Mock
}

// IsPressed provides a mock function with given fields:
func (_m *Button) IsPressed() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// NewButton creates a new instance of Button. It also registers the testing.TB interface on the mock and a cleanup function to assert the mocks expectations.
func NewButton(t testing.TB) *Button {
	mock := &Button{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
