- hosts: all
  vars_files: vars.yml
  tasks:
    - name: Set hostname
      become: true
      ansible.builtin.hostname:
        name: sunrise

    - name: Configure screen timeout
      community.general.ini_file:
        path: "{{ ansible_user_dir }}/.config/wayfire.ini"
        section: idle
        option: "{{ item.option }}"
        value: "{{ item.value }}"
      loop:
        - option: disable_on_fullscreen
          value: "false"
        - option: dpms_timeout
          value: "60"

    - name: Include setup SNMP
      ansible.builtin.include_tasks: snmp.yml
