# Based on https://github.com/JenswBE/setup/blob/main/server/tasks/zabbix-agent.yml
- name: Install and configure Zabbix agent
  become: true
  tags: ["setup", "zabbix"]
  block:
    - name: Zabbix agent - Ensure Zabbix repo is installed
      ansible.builtin.apt:
        deb: "https://repo.zabbix.com/zabbix/{{ zabbix_version }}/debian-arm64/pool/main/z/zabbix-release/zabbix-release_latest+debian{{ ansible_distribution_major_version }}_all.deb"

    - name: Zabbix agent - Ensure agent is installed
      ansible.builtin.package:
        name: zabbix-agent2
        state: present

    - name: Setup ensure-var-log-zabbix-exists.service
      register: setup_log_dir
      ansible.builtin.copy:
        src: ensure-var-log-zabbix-exists.service
        dest: /etc/systemd/system/ensure-var-log-zabbix-exists.service
        owner: root
        group: root
        mode: "644"

    - name: Setup zabbix-agent2 drop-in folder
      ansible.builtin.file:
        path: /etc/systemd/system/zabbix-agent2.service.d/
        state: directory
        owner: root
        group: root
        mode: "755"

    - name: Setup zabbix-agent2 drop-in
      register: zabbix_agent2_dropin
      ansible.builtin.copy:
        src: zabbix-agent2_dropin.service
        dest: /etc/systemd/system/zabbix-agent2.service.d/ensure-log-dir-exists.conf
        owner: root
        group: root
        mode: "644"

    - name: Reload systemd daemon
      when: setup_log_dir.changed or zabbix_agent2_dropin.changed
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Zabbix agent - Update config
      register: zabbix_agent_config
      ansible.builtin.lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: "^Server="
        line: "Server={{ query('community.dns.lookup', app_zabbix_agent_server, nxdomain_handling='fail')[0] }}"

    - name: Zabbix agent - Restart if config was changed
      when: zabbix_agent_config.changed
      ansible.builtin.service:
        name: zabbix-agent2
        state: restarted

    - name: Zabbix agent - Enable on boot
      ansible.builtin.service:
        name: zabbix-agent2
        state: started
        enabled: true
