openapi: 3.0.2
info:
  title: srv-config
  description: Service to manage configuration
  version: 0.1.0
servers: []
paths:
  /alarms:
    get:
      summary: List alarms
      operationId: alarms_list
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AlarmList"
    post:
      summary: Create alarm
      operationId: alarms_create
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Alarm"

  /alarms/{id}:
    parameters:
      - $ref: "#/components/parameters/pathID"
    get:
      summary: Get alarm
      operationId: alarms_get
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Alarm"
    put:
      summary: Update alarm
      operationId: alarms_update
      responses:
        "204":
          description: No Content
    delete:
      summary: Delete alarm
      operationId: alarms_delete
      responses:
        "204":
          description: No Content

components:
  parameters:
    pathID:
      name: id
      in: path
      description: UUID
      required: true
      schema:
        type: string
        format: uuid

  responses:
    Error:
      description: Default error response
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"

  schemas:
    Alarm:
      type: object
      required:
        - id
        - enabled
        - name
        - hour
        - minute
        - days
        - skip_next
      properties:
        id:
          type: string
          format: uuid
        enabled:
          type: boolean
        name:
          type: string
        hour:
          type: integer
        minute:
          type: integer
        days:
          type: array
          items:
            type: integer
            minimum: 0 # Monday
            maximum: 6 # Sunday
        skip_next:
          type: boolean

    AlarmList:
      type: object
      required:
        - alarms
      properties:
        alarms:
          type: array
          items:
            $ref: "#/components/schemas/Alarm"

    Error:
      type: object
      required:
        - code
        - message
      properties:
        status:
          description: HTTP status code
          type: integer
          example: 400
        code:
          $ref: "#/components/schemas/ErrorCode"
        message:
          description: Human-readable description of the error
          type: string
          example: Provided authentication token is invalid
        instance:
          description: Object to which this error is related
          type: string
          example: ""

    ErrorCode:
      description: |
        - INVALID_WEEKDAY: Provided weekday is not in range 1 (Monday) to 7 (Sunday)
        - INVALID_UUID: Provided ID is not a valid UUID
        - PARAMETER_MISSING: Required parameter is missing from the URL
        - UNKNOWN_ERROR: An unknown error occurred
      type: string
      example: UNKNOWN_ERROR
      enum:
        - INVALID_WEEKDAY
        - INVALID_UUID
        - PARAMETER_MISSING
        - UNKNOWN_ERROR
